### ISSUE TITLE
Oculus Incompatibility

### ISSUE THREAD

**Issue by Proxwian** [Kryeit/Missions#13]
### Describe the Bug

Client render crash with Embeddium, Oculus and Missions installed

### Reproduction Steps

1. Place Mechanical Exchanger block
2. Open GUI

### Expected Result

Client does not crash

### Screenshots and Videos

[crash-2024-02-07_20.40.55-client.txt](https://github.com/Kryeit/Missions/files/14199614/crash-2024-02-07_20.40.55-client.txt)

### Operating System

Mac OS

### Mod Version

0.2.11

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 42.2.20

### Other Mods

See log

**Comment by muriplz** [comment]
I cannot reproduce the issue with Create: Missions, Create, Embeddium and Oculus installed.

Could you give more details? there's too many mods in the logs

**Comment by muriplz** [comment]
reopen if 0.2.10 still crashes
