### ISSUE TITLE
Allow per-item rewards

### ISSUE THREAD

**Issue by Proxwian** [Kryeit/Missions#15]
### Describe the Suggestion

It would be nice if we can change reward per-item, not per-category only.

For example:
- If I eat "5-10" apples, I would receive 1 diamond
- If I eat "10-20" apples, I would receive 1 diamond block
- If I eat "1-3" cookies, I would receive 1 gold nugget

**Comment by muriplz** [comment]
this has been added, config version 2 supports per item rewards https://github.com/Kryeit/Missions/commit/faca7b3cd17a2066f2a10baf1f8b8ba472fa1885
