### ISSUE TITLE
Mechanical exchanger conversion destroy currency

### ISSUE THREAD

**Issue by Arcod7** [Kryeit/Missions#16]
### Describe the Bug

When we change the exchange rate in the config to a smaller number like 8 for my case, the mechanical exchanger doesn't adds ingots to output.

For exemple if I place a gold ingot, it transforms it into 8 iron ingots. But if i don't touch the output and convert an other gold ingot, it's consumed but doesn't give any more iron ingot, the output stays at 8.

There also is a small visual bug if the client have a different number than the server in exchange rate, it first shows the client number and then the server one.

### Reproduction Steps

1. Edit missions/config.json by setting "exchange-rate": "64" to "exchange-rate": "8"
2. Go in a singleplayer or multiplayer world
3. Place down a Mechanical Exchanger
4. Power it counter clockwise
5. Put two gold ingot inside
6. Notice that your second gold ingot just vanished

### Expected Result

To have 16 iron ingot, then 24, etc. and stop converting when the output is 64

### Operating System

Macos (for the client but idk for the server)

### Mod Version

0.2.10

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.5

**Comment by muriplz** [comment]
I fixed the bug, but the client-server unsync issue might be trickier to fix
