### ISSUE TITLE
Fly mission

### ISSUE THREAD

**Issue by Poke5555** [Kryeit/Missions#17]
### Describe the Suggestion

As far as i can try the current fly mission references the "distance flown" statistic which goes up when moving up and forward at the same time(run jumping, but not elytra), i feel like it should reference the "distance by elytra" statistic. 
Is there a way to adjust this in the current config? Ive tried changing "fly" to "elytra", and "aviate" but when opening the missions menu it disconnects you and displays a config error.

**Comment by muriplz** [comment]
It's an issue on which statistic we've chosen to listen to for the fly mission. Which we made a mistake! I'll find the right statistic
