### ISSUE TITLE
Loading mod error

### ISSUE THREAD

**Issue by JetStorm91** [Kryeit/Missions#18]
### Describe the Bug

when i updated Create:missions from 0.2.9 to 0.2.10 and 0.2.11, i get the Cannot invoke "String.trim()" because "in" is null error message when loading up my game, not sure if this is a common error or if it's just me

### Reproduction Steps

1. Update Create:Missions to 0.2.10 or 0.2.11
2. Start up Minecraft Launcher
3. Wait until Error shows

### Expected Result

I expected the mod to load same as it did in version 0.2.9 and go straight to the minecraft menu

### Crash Report or Log

https://pastebin.com/s4sh8uY3

### Operating System

windows 10

### Mod Version

None

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.20

### Other Mods

Alex's Mobs
All Enchantments for trade
Architectury API
Balm (Forge Edition)
Biomes O' Plenty
Block UI
Bookshelf
Carry On
Citadel
Cloth Config API
Clumps
Collective
Connectivity
Corpse
Create
Create Central Kitchen
Create Chunkloading
Create Compact Exp
Create Confectionery
Create Crafts & Additions
Create Enchantment Industry
Create Jetpack
Create Mechanical Spawner
Create Ore Excavation
Create Recycle Everything
Create Sifting
Create Slice & Dice
Create Stuff & Additions
Create: Bells & Whistles
Create: Diesel Generators
Create: Easy Structures
Create: Haven Qualities
Create: Liquid Fuel
Create: More Automation
Create: Steam & Rails
Create: Sweets & Treats
Create: Upgraded Armor
Create: Villagerology
Creativecore
Croptopia
Cupboard
Curious Api
Domum Ornamentum
Durability Tooltip
Easy Anvils
Easy Magic
Embeddium
Enchantment Descriptions
Enchantment Transfer
EpheroLib
Farmer's Delight
Fast Leaf Decay
Framed Blocks
Framework
Full Brightness Toggle
Game Menu Mod Option
Goblin Traders
Inventory Sorter
Inventory Totem
JourneyMap
Just Enough Items (JEI)
Just Enough Resources (JER)
Kotlin for Forge
Macaw's Bridges
Merge Enchantments
MineColonies
Multi-Piston
Nature's Compass
Night Config Fixes
Puzzles Lib
Repurposed Structures
Server-side Vein Miner & Tunneler
Sneaky Tree Growing
Sophisticated Backpacks
Sophisticated Core
Starter Kit
Storage Drawers
Structurize
SuperMartijin642's Config Lib
SuperMartijin642's Core Lib
TerraBlender
Time Control
TownTalk
TrashSlot
XP Tome

**Comment by muriplz** [comment]
delete config/missions/

**Comment by muriplz** [comment]
always have a backup of your missions.json, and keep updating it with new missions, I've added some, and deleted Fan missions. You need to get rid of invalid missions (blast, splash, smoke, haunt)

**Comment by JetStorm91** [comment]
> delete config/missions/
that worked, thanks for the quick response
