### ISSUE TITLE
Support for more currency settings

### ISSUE THREAD

**Issue by JiDW** [Kryeit/Missions#2]
Hello!

This mod looks amazing. It is precisely what we were hoping to find for our server!

However, we already have a currency already in place, and we can't change how it works at this point, it's too  deeply integrated in the server. The issue is, our coins works by multiple of 9, because 9 coins can be crafter into the upper coin type, and the other way around.

Right now, it seems this mod can only work with currency items with a multiple of 64. We would love to see the possibility of configuring a currency with more flexibility!

Thanks for considering this.
Regards.

**Comment by muriplz** [comment]
Alright! will try
