### ISSUE TITLE
Mission reset bug

### ISSUE THREAD

**Issue by Poke5555** [Kryeit/Missions#20]
### Describe the Bug

Several players on my server have reported that if they have 2 or more missions of the same type upon completing one of them the other will reset.
For instance 1 quest to fish 20 puffer fish and 1 quest to fish 3 lily pads, if either one is complete the progress on the other resets to 0.
Mod version: missions-forge-0.2.11
Forge version: 47.2.0

### Reproduction Steps

1. Have 2 or more quests of the same type
2. Complete either
3. The other resets

### Expected Result

for progress to be kept on the other quest

### Operating System

Win11

### Mod Version

0.2.11

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

### Other Mods

        - actuallyusefulstonecutter 4.0.3 mc 1.19.3
	- alexsmobs 1.22.7
	- appleskin 2.5.1+mc1.20.1
	- architectury 9.1.13
	- armorstatues 8.0.5
	- artifacts 9.2.2
	- athena 3.1.1
	- autoattack 1.3.5
	- balm 7.2.1
	- betterpingdisplay 1.1
	- betterstats 3.8fabric-1.20.1
	- blue_endless_jankson 1.2.2
	- bobby 5.0.0
	- bookshelf 20.1.9
	- camera 1.20.1-1.0.6
	- capes 1.5.21.20
	- cfm 7.0.0-pre36
	- chatnotify 1.1.1
	- chipped 3.0.4
	- chunky 1.3.136
	- citadel 2.5.3
	- cloth_config 11.1.118
	- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- connectivity 1.20.1-4.9
	- connectormod 1.0.0-beta.36+1.20.1
	- controlling 12.0.2
	- cookingforblockheads 16.0.1
	- corpse 1.20.1-1.0.9
	- cosmeticarmorreworked 1.20.1-v1a
	- crafttweaker 14.0.32
	- create 0.5.1.f
	- create_connected 0.7.0-mc1.20.1
	- create_crush_everything 1.0.2
	- createdeco 2.0.1-1.20.1-forge
	- creategoggles 0.5.5.f
	- createliquidfuel 2.1.0-1.20.1
	- creativecore 2.11.24
	- culllessleaves 1.20.1-1.0.5
	- cupboard 1.20.1-2.3
	- curios 5.7.0+1.20.1
	- darkmodeeverywhere 1.20.1-1.2.2
	- do_a_barrel_roll 3.5.0+1.20.1
	- easiervillagertrading 1.20-fabric0.83.0-1.5.4
	- elytra_recast 2.2.3
	- embeddium 0.3.4+mc1.20.1
	- embeddiumplus 1.2.4
	- emi 1.1.1+1.20.1+forge
	- emotecraft 2.2.7-b.build.50
	- enchantment_reveal 1.0.0
	- enchdesc 17.0.13
	- enderchests 1.20.1-1.2
	- entityculling 1.6.2
	- expandability 9.0.0
	- extremesoundmuffler 3.41-forge-1.20
	- fabric_api 0.91.0+1.10.8+1.20.1
	- fabric_api_base 0.4.30+ef105b4977
	- fabric_api_lookup_api_v1 1.6.35+67f9824077
	- fabric_biome_api_v1 13.0.12+dd0389a577
	- fabric_block_api_v1 1.0.10+0e6cb7f777
	- fabric_block_view_api_v2 1.0.0+0767707077
	- fabric_blockrenderlayer_v1 1.1.40+1d0da21e77
	- fabric_client_tags_api_v1 1.1.1+5d6761b877
	- fabric_command_api_v1 1.2.33+f71b366f77
	- fabric_command_api_v2 2.2.12+561530ec77
	- fabric_content_registries_v0 4.0.10+a670df1e77
	- fabric_convention_tags_v1 1.5.4+fa3d1c0177
	- fabric_data_generation_api_v1 12.3.3+369cb3a477
	- fabric_dimensions_v1 2.1.53+8005d10d77
	- fabric_entity_events_v1 1.5.22+b909fbe377
	- fabric_events_interaction_v0 0.6.1+0d0bd5a777
	- fabric_game_rule_api_v1 1.0.39+461110ab77
	- fabric_item_api_v1 2.1.27+2272fc7f77
	- fabric_item_group_api_v1 4.0.11+f687ac9377
	- fabric_key_binding_api_v1 1.0.36+561530ec77
	- fabric_language_kotlin 1.10.17kotlin.1.9.22
	- fabric_lifecycle_events_v1 2.2.21+afab492177
	- fabric_loot_api_v2 1.2.0+eb28f93e77
	- fabric_message_api_v1 5.1.8+52cc178c77
	- fabric_mining_level_api_v1 2.1.49+561530ec77
	- fabric_model_loading_api_v1 1.0.2+3a78c72c77
	- fabric_models_v0 0.4.1+7c3892a477
	- fabric_networking_api_v1 1.3.10+503a202477
	- fabric_object_builder_api_v1 11.1.2+2174fc8477
	- fabric_particles_v1 1.1.1+78e1ecb877
	- fabric_recipe_api_v1 1.0.20+514a076577
	- fabric_registry_sync_v0 2.3.2+1c0ea72177
	- fabric_renderer_api_v1 3.2.0+1d29b44577
	- fabric_renderer_indigo 1.5.0+67f9824077
	- fabric_rendering_data_attachment_v1 0.3.36+a6081afc77
	- fabric_rendering_fluids_v1 3.0.27+4ac5e37a77
	- fabric_rendering_v1 3.0.7+1c0ea72177
	- fabric_resource_conditions_api_v1 2.3.7+9ad825cd77
	- fabric_resource_loader_v0 0.11.9+142e25ab77
	- fabric_screen_api_v1 2.0.7+45a670a577
	- fabric_screen_handler_api_v1 1.3.29+561530ec77
	- fabric_sound_api_v1 1.0.12+4f23bd8477
	- fabric_transfer_api_v1 3.3.3+b00938ec77
	- fabric_transitive_access_wideners_v1 4.3.0+1880499877
	- fakename 1.3.1.1
	- fastipping 1.0.1
	- ferritecore 6.0.1
	- flywheel 0.6.10-7
	- forge 47.2.0
	- forgeconfigscreens 8.0.2
	- framedblocks 9.1.6
	- ftblibrary 2001.1.5
	- ftbquests 2001.3.3
	- ftbteams 2001.1.4
	- gbfabrictools 1.3.51.20
	- harvestwithease 8.0.1.0
	- ibeeditor 2.2.8
	- idletweaks 1.0.8
	- immediatelyfast 1.2.8+1.20.4
	- incendium 5.3.4
	- inventorysorter 23.0.1
	- jade 11.7.1
	- jadeaddons 5.2.2
	- jankson 5.0.1j1.2.2
	- jei 15.3.0.1
	- jeresources 1.4.0.247
	- jjelytraswap 1.7
	- jumbofurnace 4.0.0.5
	- jumpoverfences 1.3.1
	- kotlinforforge 4.10.0
	- libgui 8.0.11.20
	- libninepatch 1.2.0
	- longerchathistory 1.3
	- malilib 0.16.3
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- minihud 0.27.0
	- mining_dimension 1.20.1-1.1.0
	- missions 0.2.11
	- mixinextras 0.2.0-beta.9
	- modernfix 5.11.1+mc1.20.1
	- morered 4.0.0.4
	- mousetweaks 2.25
	- myserveriscompatible 1.0
	- observable 4.4.0
	- openpartiesandclaims 0.20.4
	- org_jetbrains_kotlin_kotlin_reflect 1.9.22
	- org_jetbrains_kotlin_kotlin_stdlib 1.9.22
	- org_jetbrains_kotlin_kotlin_stdlib_jdk7 1.9.22
	- org_jetbrains_kotlin_kotlin_stdlib_jdk8 1.9.22
	- org_jetbrains_kotlinx_atomicfu_jvm 0.23.1
	- org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm 1.7.3
	- org_jetbrains_kotlinx_kotlinx_coroutines_jdk8 1.7.3
	- org_jetbrains_kotlinx_kotlinx_datetime_jvm 0.5.0
	- org_jetbrains_kotlinx_kotlinx_serialization_cbor_jvm 1.6.2
	- org_jetbrains_kotlinx_kotlinx_serialization_core_jvm 1.6.2
	- org_jetbrains_kotlinx_kotlinx_serialization_json_jvm 1.6.2
	- pamhc2crops 1.0.3
	- pamhc2foodcore 1.0.5
	- pamhc2foodextended 1.0.0
	- pamhc2trees 1.0.2
	- paraglider 20.1.3
	- pehkui 3.7.12+1.20.1-forge
	- playeranimator 1.0.2-rc1+1.20
	- playerladder 0.6.1
	- playerrevive 2.0.24
	- puzzlesaccessapi 8.0.7
	- puzzlesapi 8.1.4
	- puzzleslib 8.1.14
	- railways 1.5.3+forge-mc1.20.1
	- rebind_narrator 2.0.2
	- recipeessentials 1.20.1-3.2
	- reeses_sodium_options 1.0.4
	- resourcefullib 2.1.23
	- rubidium 0.7.1
	- searchables 1.0.2
	- shetiphiancore 1.20.1-1.2
	- skinlayers3d 1.6.2
	- smallships 2.0.0-a2.3.3
	- sophisticatedbackpacks 3.19.8.1000
	- sophisticatedcore 0.5.116.537
	- sophisticatedstorage 0.8.68.692
	- status 1.20.1-1.0.5
	- stendhal 1.4.1-1.20
	- tcdcommons 3.8fabric-1.20.1
	- terralith 2.4.11
	- textrues_embeddium_options 0.1.4+mc1.20.1
	- trade_cycling 1.20.1-1.0.7
	- tweakeroo 0.17.1
	- useitemonblockevent 1.0.0.2
	- voicechat 1.20.1-2.4.32
	- wands 2.6.8-release
	- waveycapes 1.4.3
	- waystones 14.1.3
	- xaerominimap 23.9.7
	- xaeroworldmap 1.37.8
	- yet_another_config_lib_v3 3.2.1+1.20
	- zume 0.12.1

**Comment by muriplz** [comment]
yes, this behaviour is 100% intended, having 2 different missions and completing both with half the effort would be weird

**Comment by MrRedRhino** [comment]
It seems like they're complaining that the progress on the lillypad mission gets reset when the pufferfish one is completed which I would not have intended

**Comment by Poke5555** [comment]
Yes what rhino said, if they get 20/20 puffer fish their 2/3 lilypads resets to 0, and sometimes it rerolls the number of lilypads required to complete the quest

**Comment by muriplz** [comment]
Yes, I can confirm this bug
