### ISSUE TITLE
Option to disable some missions

### ISSUE THREAD

**Issue by Proxwian** [Kryeit/Missions#21]
### Describe the Suggestion

Maybe its already possible, but when I'm trying to delete a mission category (ride, for example), game does not launch at all.

Can you please add possibility to remove some missions categories from config file? Thanks.

**Comment by muriplz** [comment]
it has been possible since the first version of the mod. See the modrinth/curseforge page for info. If that's too much words: just delete the ride mission from missions.json **IN THE SERVER FILES**

**Comment by Proxwian** [comment]
OK, but what 'bout singleplayer? I want to remove some missions for my modpack

**Comment by muriplz** [comment]
for that too, just remove the ride mission in missions.json haha

**Comment by Proxwian** [comment]
But client is crashing when I try to launch with deleted category

**Comment by muriplz** [comment]
I see, i'll test this, can you please tell me forge/fabric, missions version and minecraft version

**Comment by Proxwian** [comment]
Forge 47.2.20, missions-forge-0.2.12.jar, Minecraft 1.20.1

**Comment by muriplz** [comment]
Thanks, will try to fix this this week

**Comment by MrRedRhino** [comment]
Is this issue still not solved?

**Comment by muriplz** [comment]
I havent been able to replicate. For this, server owners have to upload the modpack with a config/missions/missions.json. Or else singleplayers will have the default missions

**Comment by Proxwian** [comment]
I'm still not able to delete some mission categories from singleplayer

**Comment by muriplz** [comment]
then provide version and loader, and mc version, i've tested all 6 version on latest and no issue, but it's hard to test 6 things each time an issue occurs

**Comment by muriplz** [comment]
nvm im dumb didnt read the whole converstaion 
![image](https://github.com/Kryeit/Missions/assets/46825658/3761371b-2041-4a9b-92e6-0a7a178c150f)
But it's your issue, not ours.

1. you are not resetting mods/missions/ folder, since you probably have the missions created from the last missions.json
2. your missions.json is fine

**Comment by muriplz** [comment]
basically, reset your missions_data.nbt. Create: Missions cannot realize when you want it reseted on its own, so whenever you make changes to missions.json you need to reset mods/missions/missions_data.json

**Comment by muriplz** [comment]
the modpack actually would have worked, except for you, since you already joined with the previous missions.json, therefore the missions_data.nbt has your uuid with 10 missions, which are from the old missions.json, not the new one

**Comment by Proxwian** [comment]
OK, I would try it
