### ISSUE TITLE
Missions rerolls every restart

### ISSUE THREAD

**Issue by Proxwian** [Kryeit/Missions#22]
### Reproduction Steps

1. Launch server
2. Join the game
3. See missions
4. Restart server
5. Join the game
6. Get message that missions was re-rerolled

### Expected Result

As said in desc, missions would refresh every week

### Operating System

Ubuntu

### Mod Version

None

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.20

**Comment by MrRedRhino** [comment]
Is this issue still not solved?

**Comment by Proxwian** [comment]
Still not

**Comment by MrRedRhino** [comment]
Does the server process have write access in mods/missions directory?

**Comment by muriplz** [comment]
Also doesnt happen to me. Are you testing with online-mode: false? I don't think this would work with cracked server since we rely on UUID's

**Comment by muriplz** [comment]
also doesn't happen with cracked accounts. I'm unable to replicate this. Feel free to add more information!

**Comment by muriplz** [comment]
wait no, I did replicate it

**Comment by Proxwian** [comment]
Issue is still exist

**Comment by muriplz** [comment]
yes i havent updated the mod yet in CF and modrinth
