### ISSUE TITLE
Mechanical exchanger don't drop in survival

### ISSUE THREAD

**Issue by Arcod7** [Kryeit/Missions#24]
### Describe the Bug

Maybe it's intentional but the mechanical exchanger doesn't drop anything in survival, either with a pickaxe or a wrench. If it is indeed intentional, it would be great to have a parameter in the config to change that behavior

### Reproduction Steps

1. Place a mechanical exchanger
2. Destroy it with a pickaxe or a wrench
3. Nothing drops

### Expected Result

Mechanical exchanger should drop itself

### Operating System

Any, it's a server(world)-side problem

### Mod Version

0.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge 43.3.8

**Comment by muriplz** [comment]
ill update 1.19.2 with a fix

**Comment by Arcod7** [comment]
Hello, the 1.19.2 version hasn't been updated on curseforge since last month, why is this issue closed ?

**Comment by muriplz** [comment]
I will update today with a hotfix.

I decided to stop updating it, since it drains a lot of time to supports different versions.

I cannot update everything that 1.20 got, but i can bring all the "easy" fixes and additions

**Comment by Arcod7** [comment]
Hi, with the recent update (0.3.1 in 1.19.2), the mechanical exchanger is now breakable (the pickaxe icon shows in Jade and the block breaks fast) but the item still don't drop, even with a silk touch pickaxe.
