### ISSUE TITLE
Create item transport should work with the Mechanical Exchanger

### ISSUE THREAD

**Issue by Arcod7** [Kryeit/Missions#26]
### Describe the Suggestion

Funnel, chute and other Create blocs that involve item transportation should work with the Mechanical Exchanger
Right now thé only block i know that Can import and export items in and out if the Mechanical Exchanger is the Hopper but it isn't practical and is very slow

**Comment by muriplz** [comment]
nah it works, try again maybe. Keep in mind that it is like a furnace: you can only input in first slot, and you can only output in second slot

**Comment by muriplz** [comment]
either that or you are using a version that doesnt work, in that case we may need the version so i dont spend 1 hour figuring out which one it is

**Comment by muriplz** [comment]
well outputting doesnt work actually, it's a bug then

**Comment by Arcod7** [comment]
Okay i understand, I'll close this for now and I'll reopen if it doesn't work
I'm still annoyed that putting a funnel to the side of the block is not working, it's confusing to work with the block using belts with this behavior

**Comment by muriplz** [comment]
nono, you are actually right, outputting is not working, at some point it got broken. I'm fixing it

**Comment by Arcod7** [comment]
I can confirm in 1.19.2 the chute doesn't work with this block
