### ISSUE TITLE
Allow setting weight for Missions

### ISSUE THREAD

**Issue by Sadragos** [Kryeit/Missions#27]
### Describe the Suggestion

It would be very helpfull if I could define the chance/weight for each Mission type. For example increase the amount of break Missions while disabling the place mission (by setting its weight to 0)

**Comment by MrRedRhino** [comment]
Disabling mission types is already possible by removing them from the missions.json config file

**Comment by Sadragos** [comment]
I've tried that, however I've always got an NullPointerException error message, when I did so. I don't have the original error message anymore unfortunately. 

Edit: Found the message:
```
[16:21:07] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Sadragos lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "com.kryeit.missions.config.ConfigReader$Mission.rewardAmount()" because "configMission" is null
```
It kicks me with that message, as soon as I open the mission screen.

**Comment by muriplz** [comment]
The weight feature for each mission type has been added in https://github.com/Kryeit/Missions/commit/967771932a4eba9b15f045541e3bda423f041e50 
Thanks for the suggestion <3
