### ISSUE TITLE
Daily reward should be configurable

### ISSUE THREAD

**Issue by Arcod7** [Kryeit/Missions#29]
### Describe the Bug

Every day, we can claim a daily reward that is for me 16 diamonds and i find nothing in the config to change the amount and the item of that reward. Also my currency is set to createdeco coins so this is nonsense to have diamonds as a reward.

### Reproduction Steps

1. Open the missions interface
2. Claim reward
3. You obtain diamonds
...

### Expected Result

Configurable daily rewards in the config

### Operating System

Windows 11

### Mod Version

0.2.11

### Create Mod Version

0.5.1f

### Minecraft Version

1.19.2

### ModLoader and Version

Forge

**Comment by TurnrDev** [comment]
I don't think this provides that functionality by default, do you have any datapacks which might be adding that?

**Comment by Arcod7** [comment]
I've probably messed up the config somewhere
The only things i've seen is that my player have a field "diamonds: 16" in the file mods/missions/missions_data.nbt in "rewards"
What can I do to fix my problem ? delete this file ?

**Comment by TurnrDev** [comment]
Could I see your config? We'd love to find a way to do daily missions on our server

**Comment by Arcod7** [comment]
There's nothing in my config about this 
Here's the config missions.json
https://ctxt.io/2/AAAoXL46Fg

**Comment by Arcod7** [comment]
I don't know how it works but it's probably that after claiming a reward, if it's not in the currency.json, it's not deleted and since my server restart daily, at each restart, i can claim that reward

**Comment by muriplz** [comment]
> I've probably messed up the config somewhere The only things i've seen is that my player have a field "diamonds: 16" in the file mods/missions/missions_data.nbt in "rewards" What can I do to fix my problem ? delete this file ?

I see, it could be an issue about saving. Since this happens everyday, does your server restart everyday?
The .nbt file might not be saving properly when the server stops, and it rolls back to it's last state, where the stashed rewards are still there for your UUID

**Comment by muriplz** [comment]
Only reason I can think of is that you are force-stopping the server, and not letting things save.

Maybe we can add a saving whenever the autosave of the world happens

**Comment by Arcod7** [comment]
Yes, I don't know why but my server wouldn't stop normally and I had to force stop it but now with mods updates, this problem is gone.

I've removed the buggy line in the config and now everything is fine.

I still think that it's a nice feature to have daily reward but it's not the intended way of having it
