### ISSUE TITLE
cant have more than 4 currencys

### ISSUE THREAD

**Issue by Cornbread0022** [Kryeit/Missions#33]
### Describe the Bug

i try to add to the list of currency's, it then deletes the last currency i added

### Reproduction Steps

1.adding "minecraft:gold_ingot" (for example) to the list of currency's
2.save the file
3.re open the file
4.its not there anymore

### Expected Result

to have the currency in the list

### Screenshots and Videos

https://github.com/Kryeit/Missions/assets/58529249/11719ed9-c407-4feb-ad2e-ad0fe5eec925

### Operating System

windows 10

### Mod Version

0.3.2

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

fabric 0.15.10

### Other Mods

there was no crash

**Comment by muriplz** [comment]
well this is weird, no idea what's happening here

Seems an issue with your Visual Studio stuff not saving?
Does this issue happen with any other file, or do you still have this issue?

**Comment by Cornbread0022** [comment]
Currently it only does it with that specific file 
So I'm not sure if it is the saving that's the problem :(

**Comment by MrRedRhino** [comment]
Is the server running? If so, you need to stop it, edit and save the file and start the server again

**Comment by Cornbread0022** [comment]
No it is not running, it's a single player world I'm doing tests in so that it can be added to a server
Edit-the game isn't even open in the background either

**Comment by MrRedRhino** [comment]
The same applies, if the world is open in your minecraft client

**Comment by MrRedRhino** [comment]
Atleast I think so

**Comment by Cornbread0022** [comment]
It isn't open 😅
In the vid you can see there is no Minecraft icon at the bottom, I made sure it wasn't open when I recorded it

**Comment by muriplz** [comment]
if it isnt open, missions mod is not running. That means that it's likely an issue in your pc/VSCode bug/ something

**Comment by Cornbread0022** [comment]
Hmm, I'm unsure of another file editing thing like the one I have.
I'll look around tho

**Comment by Cornbread0022** [comment]
Looks like it was an issue with the thing that edits the file, just using notepad works
Very strange that it doesn't work with that specific file
