### ISSUE TITLE
Missions file keeps generating with createdeco coins, even when currency file is changed

### ISSUE THREAD

**Issue by MatchTerm** [Kryeit/Missions#34]
### Describe the Bug

Essentially, even when I have modified the currency.json file to use numismatics currency and deleted the old missions.json file, the regenerated file still uses createdeco coins instead. Am I doing something wrong or is it a bug?

### Reproduction Steps

1. Have create:numismatics, create deco and create: missions installed
2. Modify the currency.json file to use numi's money and delete the old missions.json file to force a regeneration
3. Observe as the regenerated file, after restarting the game, still uses create deco coins.

### Expected Result

I expect the new missions.json file to use the currency in the currency.json file instead of the default.

### Screenshots and Videos

![image](https://github.com/Kryeit/Missions/assets/28060353/8b5a3f73-e08f-453a-a7de-65ba091f5671)
![image](https://github.com/Kryeit/Missions/assets/28060353/02de6241-c5ff-42a2-b115-2402af65c96f)

### Operating System

Windows 11

### Mod Version

0.3.2

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.20

**Comment by muriplz** [comment]
the missions.json has to be configured manually for each server, the createdeco coins appear as this is a "mockup" config file that uses their coins, you have to change those manually

**Comment by MatchTerm** [comment]
> the missions.json has to be configured manually for each server, the createdeco coins appear as this is a "mockup" config file that uses their coins, you have to change those manually

I see. Apologies, just assumed it would work like that.

**Comment by muriplz** [comment]
no worries, I'm planning to rework how currencies are registered and configure the exchange rate of each, maybe i'll add placeholders like %currency[i]% in the missions.json
