### ISSUE TITLE
Missions removed from the config cause the client to crash

### ISSUE THREAD

**Issue by TurnrDev** [Kryeit/Missions#35]
https://github.com/Kryeit/Missions/blob/3d7905852a29dec32cc200799d0522b0a8063b66/common/src/main/java/com/kryeit/missions/DataStorage.java#L256

I have a `fly` mission assigned to myself but have removed the fly missions from the config file as we have elytra boosting disabled on the server. Whenever I press `h` to load the missions menu, I get the following error:

```
Internal Exception: java.long.NullPointerException: Cannot invoke "com.kryeit.missions.config.ConfigReader$Mission.rewardAmount()" because "configMission" is null
```
Looks like we need some null safety checks here. I don't want to delete the mission_data.nbt file as we have several players who have made progress on their missions

**Comment by muriplz** [comment]
It's probably because you deleted a missionType and that player still has a flying mission.

How to solve it for now:
- Use NBTExplorer and delete that player's entry

I'll make a fix so those get rerolled for next update

**Comment by muriplz** [comment]
The player will still get kicked the first time, but relogging for a second time will fix it!
if the player joins with a mission that is no longer on the missions.json, that missions will get rerolled!

**Comment by TurnrDev** [comment]
Hey, it's not a perfect fix, but I appreciate a fix nonetheless. You're the G!
