### ISSUE TITLE
All missions are of the same type

### ISSUE THREAD

**Issue by Sadragos** [Kryeit/Missions#36]
### Describe the Bug

After a weekly reroll all Missions are of the same type for every player.

### Reproduction Steps

1. Changed missions.json over the weekend and deleted missions data file (statistic missions were causing problems, because minecraft statistics were not working properly)
2. Logged in on monday to only see eat missions. Every player reports to have missions from only one category (although the category varies per player)

### Expected Result

Have a mixed Bag of missions

### Screenshots and Videos

![only_food](https://github.com/Kryeit/Missions/assets/4946071/405ce17f-cf83-4055-b881-a043f9260bc9)

### Operating System

Ubuntu 22

### Mod Version

0.3.2

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

**Comment by Sadragos** [comment]
Here's a pastebin-link of the config: https://pastebin.com/k75wrz4q

**Comment by muriplz** [comment]
Thanks for the bug report, I will fix it for next version!

**Comment by Sadragos** [comment]
Additional Info: When rerolling a single task the categories are random as expected - so the issue seems to only be in the weekly complete reroll.
