### ISSUE TITLE
[1.20.1 Forge] Can't launch the game - Crash

### ISSUE THREAD

**Issue by Proxwian** [Kryeit/Missions#40]
### Describe the Bug

[crash-2024-05-09_10.37.47-fml.txt](https://github.com/Kryeit/Missions/files/15259140/crash-2024-05-09_10.37.47-fml.txt)

### Reproduction Steps

1. Install 0.3.3 version
2. Try to launch the game
...

### Additional Context

I've removed config/missions and mods/missions folders after update

**Comment by muriplz** [comment]
I've seen that there is some issues with the forge version, I'm working on a fix
