### ISSUE TITLE
rerolling missions

### ISSUE THREAD

**Issue by Cornbread0022** [Kryeit/Missions#42]
### Describe the Bug

when rerolling a mission, it will pick 1 of 2 types of missions consistantly

### Reproduction Steps

1. go to missions
2. reroll selected
3. it becomes 1 of 2 types of missions 
(it appears to determine the mission on boot up of game, further testing required)
4. when rerolling again, it switches to the other mission of the 2 picked 
(if 'place blocks' and 'ride animal' missions are chosen, then one will become the other and vice versa)

https://github.com/Kryeit/Missions/assets/58529249/0809c4ac-6462-4900-b6ba-fb723f47cafc

### Expected Result

a random mission of the X amount total would be picked with a highly unlikelihood chance of a repeat
(i dont remember how many missions there are total)

**Comment by muriplz** [comment]
version?

**Comment by Cornbread0022** [comment]
1.20.1
missions:0.3.2

**Comment by muriplz** [comment]
can you test with 0.3.4?

**Comment by Cornbread0022** [comment]
I can, ittle be a few hours til I can tho

**Comment by Cornbread0022** [comment]
it now appears to crash the game entirely

[latest.log](https://github.com/Kryeit/Missions/files/15284986/latest.log)

**Comment by Cornbread0022** [comment]
i really didnt mean for the log to look suspicious
i thought it would show the text inside

**Comment by Cornbread0022** [comment]
same happens with 0.3.3
[latest.log](https://github.com/Kryeit/Missions/files/15285002/latest.log)

**Comment by muriplz** [comment]
Please delete config/missions/ folder as said in the changelog

**Comment by Cornbread0022** [comment]
Will do

**Comment by muriplz** [comment]
once there you have the new rerolling logic, so maybe this issue is fixed :)

**Comment by Cornbread0022** [comment]
it functions normally now :)
thank you for your help :)
