### ISSUE TITLE
[1.20.1 Forge] Can't launch the game - Still not working 

### ISSUE THREAD

**Issue by ii-xz** [Kryeit/Missions#43]
### Describe the Bug

[crash-2024-05-09_10.37.47-fml.txt](https://github.com/Kryeit/Missions/files/15284093/crash-2024-05-09_10.37.47-fml.txt)
I tried to launch Minecraft with this mod, but it keeps crashing, me and my friends have tried 0.3.3 and saw that it wasn't working, but when 0.3.4 came out we tried it, and still could not launch the game.

### Reproduction Steps

1. Download 0.3.4
2. Launch Try to launch the game
...

### Expected Result

I expected the game to load into the Minecraft main menu.

**Comment by MatchTerm** [comment]
Same, having an error on mod load
[crash-2024-05-11_21.30.00-fml.txt](https://github.com/Kryeit/Missions/files/15284105/crash-2024-05-11_21.30.00-fml.txt)

**Comment by muriplz** [comment]
you need to delete config/missions/ folder for it to work
