### ISSUE TITLE
Crash Server tick loop

### ISSUE THREAD

**Issue by Rodrigo816** [Kryeit/Missions#46]
### Describe the Bug

When loading my world, it crashes randomly. I've deleted all missions folders to recreate them, but it still crashes sporadically, only when loading a world.
**Forge:** 47.2.20
**Missions:** 0.3.4
[crash-2024-05-20_00.21.12-server.txt](https://github.com/Kryeit/Missions/files/15371366/crash-2024-05-20_00.21.12-server.txt)

### Reproduction Steps

1. Load a world
2.
3.
...

**Comment by Rodrigo816** [comment]
Multiple users of my modpack have reported this issue. I really like the mod and want to keep it since it plays a crucial role, but it is affecting people.
[crash-2024-05-20_00.17.31-server.txt](https://github.com/Kryeit/Missions/files/15371448/crash-2024-05-20_00.17.31-server.txt)

**Comment by muriplz** [comment]
ok ill push a new version soon

**Comment by Rodrigo816** [comment]
> ok ill push a new version soon

Do you know what is causing?

**Comment by Proxwian** [comment]
It still happens. Fix?

**Comment by muriplz** [comment]
working on a fix still, almost done

**Comment by muriplz** [comment]
it's forge-sided code the one that has the bug

**Comment by Rodrigo816** [comment]
Ohh ok, best of luck.

**Comment by MaouTsuki** [comment]
Have you been able to find a fix or get any closer to so?

**Comment by muriplz** [comment]
yes, should be fixed. If you are still having issues please share the crash log

**Comment by Rodrigo816** [comment]
> yes, should be fixed. If you are still having issues please share the crash log

so no new version release?

**Comment by muriplz** [comment]
> > yes, should be fixed. If you are still having issues please share the crash log
> 
> so no new version release?

I don't really know what you mean, your bug report is on 0.3.4, and there is a 0.3.6 version (that changes mission shuffling drastically)

I really cannot fix a bug that I dont know exists, and even less with a crash log of a previous version
