### ISSUE TITLE
Unable to open the Missions menu

### ISSUE THREAD

**Issue by INV-PLA** [Kryeit/Missions#49]
### Describe the Bug

![image](https://github.com/user-attachments/assets/a53dd049-a54e-42b9-8d6c-735f4b24b615)
![image](https://github.com/user-attachments/assets/ae66019f-a32b-4300-a806-344b66c1b5f8)

### Reproduction Steps

1.Open the Missions menu

### Additional Context, Mod version and loader

Forge 47.3.5
missions-forge-0.3.6

**Comment by muriplz** [comment]
can you send latest.log

**Comment by INV-PLA** [comment]
[latest.log](https://github.com/user-attachments/files/16311455/latest.log)


> can you send latest.log
