### ISSUE TITLE
Eating missions do not progress

### ISSUE THREAD

**Issue by uberswe** [Kryeit/Missions#51]
### Describe the Bug

I run a Fabric server behind a Velocity proxy which shouldn't matter. I can do compacting, mixing, feeding animals, and many of the other missions just fine. However, eating and harvesting missions do not seem to work. I am not seeing any errors in the console.
[currency.json](https://github.com/user-attachments/files/17194110/currency.json)
[config.json](https://github.com/user-attachments/files/17194111/config.json)
[missions.json](https://github.com/user-attachments/files/17194112/missions.json)

### Reproduction Steps

1. Get a missions such as "Eat 3 of Golden Carrot"
2. Eat 3 Golden Carrots
3. Your progress is still 0/3

### Expected Result

I expect to finish the mission with 3/3 Golde carrots eaten

### Additional Context, Mod version and loader

Attached logs, this is Create: Missions 0.3.6 on Fabric
[latest (5).log](https://github.com/user-attachments/files/17194142/latest.5.log)

**Comment by muriplz** [comment]
the eating mission is solved for next release, which should be soon.
As for the harvesting mission, will check! 
thanks for reporting

**Comment by uberswe** [comment]
I also noticed that we sometimes get missions to crush platinum ores even though Create doesn’t have any platinum

**Comment by muriplz** [comment]
yeah, it does, but its a hidden item.
![image](https://github.com/user-attachments/assets/8ce66061-f1fe-4255-8153-7d42ac166864)
the issue is that tag. Tag support wont be a thing in the next update due to weirdness in tags
